services:
  tranga-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - tranga-downloads:/Manga
      - tranga-settings:/usr/share/tranga-api
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - tranga_dev_network
    environment:
      - POSTGRES_HOST=tranga-pg
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - MATCH_EXACT_CHAPTER_NAME=false
    # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
    # user: root
  tranga-website:
    image: glax/tranga-website:latest
    restart: unless-stopped
    networks:
      - tranga_dev_network
    environment:
      - API_URL=http://tranga-api:6531
  tranga-pg:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tranga_dev_network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
  tranga-downloads:
  tranga-settings:

networks:
  tranga_dev_network:
