version: '3.8'

services:
  tranga-api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - tranga_dev_network
    environment:
      - POSTGRES_HOST=tranga-pg
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - MATCH_EXACT_CHAPTER_NAME=false
    
    # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
    # user: root

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  tranga-website:
    image: glax/tranga-website:latest
    restart: unless-stopped
    networks:
      - tranga_dev_network
    ports:
      - "9555:80"
    environment:
      - API_URL=http://tranga-api:6531
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  tranga-pg:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tranga_dev_network
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
      
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:

networks:
  tranga_dev_network:
